config/routes.rb
Diditme::Application.routes.draw do
  get "task/index"
  get "task/show"
  get "task/new"
  get "home/index"
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => "sessions#destroy", :as => :signout
  match '/list' => "task#index", :as => :list
  
  root :to => "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many  :tasks
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["user_info"]["account"]
      user.email= auth["user_info"]["username"]
      user.token = auth["credentials"]['token']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def authenticate
    redirect_to root_url, :notice => "Please login first!" unless current_user
  end
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to list_path, :notice => "Signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_filter :authenticate
  def index
    
  end

  def show
  end

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(current_user)
    gravatar_id = Digest::MD5::hexdigest(current_user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=24"
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/home/index.html.erb
<div id="home">
	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	<div id="review" class="intro">
		<div id="review_intro" class="left">
			<h1>Review achievements has never been so easy...</h1>
			<p>Reviewing your achievements on daily bases has never been so easy.</p>
		</div>
		<div id="review_img" class="right"><%= image_tag 'dummy.png',:width=>'320px' %></div>
	</div>
	<div id="calendar" class="intro">
		<div id="calendar_img" class="left">
			<%= image_tag 'dummy.png', :width => '320px'%>
		</div>
		<div id="calendar_intro" class="right">
			<h1>View achievements in the calendar view</h1>
			<p>Take the calendar view, to check your achievements more clearly</p>
		</div>
	</div>
	<div id="graph" class="intro">
		<div id="graph_intro" class="left">
			<h1>Summary achievements with graphic</h1>
			<p>Your achievements, with beautiful graphics.</p>
		</div>
		<div id="graph_img" class="right"><%= image_tag 'dummy.png', :width=>'320px'%></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "DidIt | What did you do today?" %></title>
    <%= stylesheet_link_tag "reset","typography","application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id='logo'><div id='logo_typography'>Did it</div></div>
	<div id='login'>
		<% if current_user %>
			<%= image_tag avatar_url(current_user) %> Welcome, <%= current_user.name %>!
			Not you? <%= link_to "Sign Out", signout_path %>
		<% else %>
			<%= link_to "Sign in with Doit.im", '/auth/doit'%>
		<% end %>
	</div>
    <div id="container">
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/task/index.html.erb
<div id="days">
	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	<div class="date">Date</div>
	<div calss="biref_list">
		
	</div>
</div>

app/views/task/new.html.erb
<h1>Task#new</h1>
<p>Find me in app/views/task/new.html.erb</p>

app/views/task/show.html.erb
<h1>Task#show</h1>
<p>Find me in app/views/task/show.html.erb</p>